numero1 = float(input('Digite um numero: '))
numero2 = float(input('Digite outro numero: '))
numero3 = float(input('Digite um ultimo numero: '))
maior_numero = max(numero1,numero2,numero3)
print(f'O maior numero é {maior_numero}')